apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-conversao
spec:
  selector:
    matchLabels:
      app: website-conversao
  template:
    metadata:
      labels:
        app: website-conversao
    spec:
      containers:
      - name: site-conversao
        image: akira78/conversao-temperatura:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  selector:
    app: website-conversao
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30000
  type: NodePort